SET FOREIGN_KEY_CHECKS = 0;

-- 1. Consultorio -> Estado
ALTER TABLE Consultorio
DROP FOREIGN KEY IF EXISTS FK_ESTADO_CONSULTORIO;
ALTER TABLE Consultorio
    DROP FOREIGN KEY IF EXISTS FK_ESTADO_CONSULTORIO;
ALTER TABLE Consultorio
    ADD CONSTRAINT FK_ESTADO_CONSULTORIO
    FOREIGN KEY (id_estado) REFERENCES Estado(id_estado)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- 2. Usuario -> Tipo_Usuario, Consultorio, Escuela
ALTER TABLE Usuario
    DROP FOREIGN KEY IF EXISTS FK_TIPOUSUARIO_USUARIO,
    DROP FOREIGN KEY IF EXISTS FK_CONSULTORIO_USUARIO,
    DROP FOREIGN KEY IF EXISTS FK_ESCUELA_USUARIO;
ALTER TABLE Usuario
    ADD CONSTRAINT FK_TIPOUSUARIO_USUARIO
        FOREIGN KEY (id_tipo_usuario) REFERENCES Tipo_Usuario(id_tipo_usuario)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT FK_CONSULTORIO_USUARIO
        FOREIGN KEY (id_consultorio) REFERENCES Consultorio(id_consultorio)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT FK_ESCUELA_USUARIO
        FOREIGN KEY (id_escuela) REFERENCES Escuela(id_escuela)
        ON DELETE RESTRICT ON UPDATE CASCADE;

-- 3. Paciente -> Tipo_Sangre, Consultorio, Usuario
ALTER TABLE Paciente
    DROP FOREIGN KEY IF EXISTS FK_TIPOSANGRE_PACIENTE,
    DROP FOREIGN KEY IF EXISTS FK_CONSULTORIO_PACIENTE,
    DROP FOREIGN KEY IF EXISTS FK_USUARIO_PACIENTE;
ALTER TABLE Paciente
    ADD CONSTRAINT FK_TIPOSANGRE_PACIENTE
        FOREIGN KEY (id_tipo_sangre) REFERENCES Tipo_Sangre(id_tipo_sangre)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT FK_CONSULTORIO_PACIENTE
        FOREIGN KEY (id_consultorio) REFERENCES Consultorio(id_consultorio)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT FK_USUARIO_PACIENTE
        FOREIGN KEY (id_usuario) REFERENCES Usuario(id_usuario)
        ON DELETE RESTRICT ON UPDATE CASCADE;

-- 4. Cita -> Paciente, Consultorio, Estado_Cita, Tratamiento
ALTER TABLE Cita
    DROP FOREIGN KEY IF EXISTS FK_PACIENTE_CITA,
    DROP FOREIGN KEY IF EXISTS FK_CONSULTORIO_CITA,
    DROP FOREIGN KEY IF EXISTS FK_ESTADOCITA_CITA,
    DROP FOREIGN KEY IF EXISTS FK_TRATAMIENTO_CITA;
ALTER TABLE Cita
    ADD CONSTRAINT FK_PACIENTE_CITA
        FOREIGN KEY (id_paciente) REFERENCES Paciente(id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT FK_CONSULTORIO_CITA
        FOREIGN KEY (id_consultorio) REFERENCES Consultorio(id_consultorio)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT FK_ESTADOCITA_CITA
        FOREIGN KEY (id_estado_cita) REFERENCES Estado_Cita(id_estado_cita)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT FK_TRATAMIENTO_CITA
        FOREIGN KEY (id_tratamiento) REFERENCES Tratamiento(id_tratamiento)
        ON DELETE RESTRICT ON UPDATE CASCADE;

-- 5. Medicamento -> Denominacion_General, Denominacion_Quimica, Consultorio
ALTER TABLE Medicamento
    DROP FOREIGN KEY IF EXISTS FK_DENGENERAL_MEDICAMENTO,
    DROP FOREIGN KEY IF EXISTS FK_DENQUIMICA_MEDICAMENTO,
    DROP FOREIGN KEY IF EXISTS FK_CONSULTORIO_MEDICAMENTO;
ALTER TABLE Medicamento
    ADD CONSTRAINT FK_DENGENERAL_MEDICAMENTO
        FOREIGN KEY (id_denominacion_general) REFERENCES Denominacion_General(id_denominacion_general)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT FK_DENQUIMICA_MEDICAMENTO
        FOREIGN KEY (id_denominacion_quimica) REFERENCES Denominacion_Quimica(id_denominacion_quimica)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT FK_CONSULTORIO_MEDICAMENTO
        FOREIGN KEY (id_consultorio) REFERENCES Consultorio(id_consultorio)
        ON DELETE RESTRICT ON UPDATE CASCADE;

-- 6. Nota_Evolucion -> Paciente
ALTER TABLE Nota_Evolucion
    DROP FOREIGN KEY IF EXISTS FK_PACIENTE_NOTAEVOLUCION;
ALTER TABLE Nota_Evolucion
    ADD CONSTRAINT FK_PACIENTE_NOTAEVOLUCION
    FOREIGN KEY (id_paciente) REFERENCES Paciente(id_paciente)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- 7. Documento -> Tipo_Documento
ALTER TABLE Documento
    DROP FOREIGN KEY IF EXISTS FK_TIPODOCUMENTO_DOCUMENTO;
ALTER TABLE Documento
    ADD CONSTRAINT FK_TIPODOCUMENTO_DOCUMENTO
    FOREIGN KEY (id_tipo_documento) REFERENCES Tipo_Documento(id_tipo_documento)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- 8. Documento_Paciente -> Documento, Paciente
ALTER TABLE Documento_Paciente
    DROP FOREIGN KEY IF EXISTS FK_DOCUMENTO_DOCUMENTOPACIENTE,
    DROP FOREIGN KEY IF EXISTS FK_PACIENTE_DOCUMENTOPACIENTE;
ALTER TABLE Documento_Paciente
    ADD CONSTRAINT FK_DOCUMENTO_DOCUMENTOPACIENTE
        FOREIGN KEY (id_documento) REFERENCES Documento(id_documento)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT FK_PACIENTE_DOCUMENTOPACIENTE
        FOREIGN KEY (id_paciente) REFERENCES Paciente(id_paciente)
        ON DELETE CASCADE ON UPDATE CASCADE;

-- 9. Ticket -> Tipo_Pago, Usuario
ALTER TABLE Ticket
    DROP FOREIGN KEY IF EXISTS FK_TIPOPAGO_TICKET,
    DROP FOREIGN KEY IF EXISTS FK_USUARIO_TICKET;
ALTER TABLE Ticket
    ADD CONSTRAINT FK_TIPOPAGO_TICKET
        FOREIGN KEY (id_tipo_pago) REFERENCES Tipo_Pago(id_tipo_pago)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT FK_USUARIO_TICKET
        FOREIGN KEY (id_usuario) REFERENCES Usuario(id_usuario)
        ON DELETE RESTRICT ON UPDATE CASCADE;

-- 10. Ticket_Medicamento -> Ticket, Medicamento
ALTER TABLE Ticket_Medicamento
    DROP FOREIGN KEY IF EXISTS FK_TICKET_TICKETMEDICAMENTO,
    DROP FOREIGN KEY IF EXISTS FK_MEDICAMENTO_TICKETMEDICAMENTO;
ALTER TABLE Ticket_Medicamento
    ADD CONSTRAINT FK_TICKET_TICKETMEDICAMENTO
        FOREIGN KEY (id_ticket) REFERENCES Ticket(id_ticket)
        ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT FK_MEDICAMENTO_TICKETMEDICAMENTO
        FOREIGN KEY (id_medicamento) REFERENCES Medicamento(id_medicamento)
        ON DELETE RESTRICT ON UPDATE CASCADE;

-- 11. Ticket_Caja -> Ticket, Corte_Caja
ALTER TABLE Ticket_Caja
    DROP FOREIGN KEY IF EXISTS FK_TICKET_TICKETCAJA,
    DROP FOREIGN KEY IF EXISTS FK_CORTECAJA_TICKETCAJA;
ALTER TABLE Ticket_Caja
    ADD CONSTRAINT FK_TICKET_TICKETCAJA
        FOREIGN KEY (id_ticket) REFERENCES Ticket(id_ticket)
        ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT FK_CORTECAJA_TICKETCAJA
        FOREIGN KEY (id_corte_caja) REFERENCES Corte_Caja(id_corte_caja)
        ON DELETE RESTRICT ON UPDATE CASCADE;

-- 12. Corte_Caja -> Usuario
ALTER TABLE Corte_Caja
    DROP FOREIGN KEY IF EXISTS FK_USUARIO_CORTECAJA;
ALTER TABLE Corte_Caja
    ADD CONSTRAINT FK_USUARIO_CORTECAJA
    FOREIGN KEY (id_usuario) REFERENCES Usuario(id_usuario)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- 13. Medicamento -> Via_Administrar_Medicamento
ALTER TABLE Medicamento
    DROP FOREIGN KEY IF EXISTS FK_MEDICAMENTO_VIAADMINISTRARMEDICAMENTO;
ALTER TABLE Medicamento
    ADD CONSTRAINT FK_MEDICAMENTO_VIAADMINISTRARMEDICAMENTO
    FOREIGN KEY(id_via_administrar_medicamento) REFERENCES Via_Administrar_Medicamento(id_via_administrar_medicamento)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- 14. Receta_Medicamento -> Receta, Medicamento
ALTER TABLE Receta_Medicamento
    DROP FOREIGN KEY IF EXISTS FK_RECETAMEDICAMENTO_RECETA,
    DROP FOREIGN KEY IF EXISTS FK_RECETAMEDICAMENTO_MEDICAMENTO;
ALTER TABLE Receta_Medicamento
    ADD CONSTRAINT FK_RECETAMEDICAMENTO_RECETA
    FOREIGN KEY (id_receta) REFERENCES Receta(id_receta)
    ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT FK_RECETAMEDICAMENTO_MEDICAMENTO
    FOREIGN KEY (id_medicamento) REFERENCES Medicamento(id_medicamento)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- 15. Recta -> Usuario, Paciente
ALTER TABLE Receta
    DROP FOREIGN KEY IF EXISTS FK_RECETA_USUARIO,
    DROP FOREIGN KEY IF EXISTS FK_RECETA_PACIENTE;
ALTER TABLE Receta
    ADD CONSTRAINT FK_RECETA_USUARIO
    FOREIGN KEY (id_usuario) REFERENCES Usuario(id_usuario)
    ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT FK_RECETA_PACIENTE
    FOREIGN KEY (id_paciente) REFERENCES Paciente(id_paciente)
    ON DELETE RESTRICT ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS = 1;
