# Form implementation generated from reading ui file 'consultorio_crear.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_d_crear_consultorio(object):
    def setupUi(self, d_crear_consultorio):
        d_crear_consultorio.setObjectName("d_crear_consultorio")
        d_crear_consultorio.resize(832, 463)
        d_crear_consultorio.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.label = QtWidgets.QLabel(parent=d_crear_consultorio)
        self.label.setGeometry(QtCore.QRect(340, 10, 191, 51))
        self.label.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=d_crear_consultorio)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 61, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=d_crear_consultorio)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 51, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=d_crear_consultorio)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 151, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=d_crear_consultorio)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 61, 18))
        self.label_5.setObjectName("label_5")
        self.le_localidad = QtWidgets.QLineEdit(parent=d_crear_consultorio)
        self.le_localidad.setGeometry(QtCore.QRect(110, 160, 131, 25))
        self.le_localidad.setObjectName("le_localidad")
        self.le_calle = QtWidgets.QLineEdit(parent=d_crear_consultorio)
        self.le_calle.setGeometry(QtCore.QRect(70, 130, 231, 25))
        self.le_calle.setObjectName("le_calle")
        self.le_nombre_consultorio = QtWidgets.QLineEdit(parent=d_crear_consultorio)
        self.le_nombre_consultorio.setGeometry(QtCore.QRect(80, 100, 431, 25))
        self.le_nombre_consultorio.setObjectName("le_nombre_consultorio")
        self.label_6 = QtWidgets.QLabel(parent=d_crear_consultorio)
        self.label_6.setGeometry(QtCore.QRect(310, 130, 131, 18))
        self.label_6.setObjectName("label_6")
        self.le_num_exterior = QtWidgets.QLineEdit(parent=d_crear_consultorio)
        self.le_num_exterior.setGeometry(QtCore.QRect(440, 130, 113, 25))
        self.le_num_exterior.setObjectName("le_num_exterior")
        self.label_7 = QtWidgets.QLabel(parent=d_crear_consultorio)
        self.label_7.setGeometry(QtCore.QRect(570, 130, 131, 18))
        self.label_7.setObjectName("label_7")
        self.le_num_interior = QtWidgets.QLineEdit(parent=d_crear_consultorio)
        self.le_num_interior.setGeometry(QtCore.QRect(700, 120, 113, 25))
        self.le_num_interior.setObjectName("le_num_interior")
        self.label_8 = QtWidgets.QLabel(parent=d_crear_consultorio)
        self.label_8.setGeometry(QtCore.QRect(260, 160, 41, 18))
        self.label_8.setObjectName("label_8")
        self.le_cp = QtWidgets.QLineEdit(parent=d_crear_consultorio)
        self.le_cp.setGeometry(QtCore.QRect(300, 160, 113, 25))
        self.le_cp.setObjectName("le_cp")
        self.label_9 = QtWidgets.QLabel(parent=d_crear_consultorio)
        self.label_9.setGeometry(QtCore.QRect(430, 160, 91, 18))
        self.label_9.setObjectName("label_9")
        self.le_municipio = QtWidgets.QLineEdit(parent=d_crear_consultorio)
        self.le_municipio.setGeometry(QtCore.QRect(520, 160, 211, 25))
        self.le_municipio.setObjectName("le_municipio")
        self.cb_estado = QtWidgets.QComboBox(parent=d_crear_consultorio)
        self.cb_estado.setGeometry(QtCore.QRect(80, 190, 171, 26))
        self.cb_estado.setMaxCount(34)
        self.cb_estado.setObjectName("cb_estado")
        self.pb_crear_usuario = QtWidgets.QPushButton(parent=d_crear_consultorio)
        self.pb_crear_usuario.setGeometry(QtCore.QRect(675, 230, 111, 26))
        self.pb_crear_usuario.setObjectName("pb_crear_usuario")

        self.retranslateUi(d_crear_consultorio)
        QtCore.QMetaObject.connectSlotsByName(d_crear_consultorio)

    def retranslateUi(self, d_crear_consultorio):
        _translate = QtCore.QCoreApplication.translate
        d_crear_consultorio.setWindowTitle(_translate("d_crear_consultorio", "Crear consultorio"))
        self.label.setText(_translate("d_crear_consultorio", "# Consultorio"))
        self.label_2.setText(_translate("d_crear_consultorio", "Nombre:"))
        self.label_3.setText(_translate("d_crear_consultorio", "Calle:"))
        self.label_4.setText(_translate("d_crear_consultorio", "Localidad:"))
        self.label_5.setText(_translate("d_crear_consultorio", "Estado:"))
        self.label_6.setText(_translate("d_crear_consultorio", "Número exterior:"))
        self.label_7.setText(_translate("d_crear_consultorio", "Número interior:"))
        self.label_8.setText(_translate("d_crear_consultorio", "C.P.:"))
        self.label_9.setText(_translate("d_crear_consultorio", "Municipio:"))
        self.pb_crear_usuario.setText(_translate("d_crear_consultorio", "Crear usuario"))
