# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 546)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 140, 331, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.le_usuario = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.le_usuario.setInputMask("")
        self.le_usuario.setText("")
        self.le_usuario.setObjectName("le_usuario")
        self.verticalLayout.addWidget(self.le_usuario)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.le_contrasena = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.le_contrasena.setInputMask("")
        self.le_contrasena.setText("")
        self.le_contrasena.setObjectName("le_contrasena")
        self.verticalLayout.addWidget(self.le_contrasena)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pb_ingresar = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pb_ingresar.setAutoDefault(False)
        self.pb_ingresar.setDefault(False)
        self.pb_ingresar.setFlat(False)
        self.pb_ingresar.setObjectName("pb_ingresar")
        self.gridLayout.addWidget(self.pb_ingresar, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 40, 564, 27))
        self.label.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label.setObjectName("label")
        self.wg_imagen_sihmed = QtWidgets.QWidget(parent=self.centralwidget)
        self.wg_imagen_sihmed.setGeometry(QtCore.QRect(10, 20, 120, 80))
        self.wg_imagen_sihmed.setObjectName("wg_imagen_sihmed")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SIHMED"))
        self.le_usuario.setPlaceholderText(_translate("MainWindow", "Usuario"))
        self.le_contrasena.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.pb_ingresar.setText(_translate("MainWindow", "Ingresar"))
        self.label.setText(_translate("MainWindow", "## Sistema Integral Hospitalario y de Medicamentos"))
