# Form implementation generated from reading ui file 'menu_principal.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_d_menu_principal(object):
    def setupUi(self, d_menu_principal):
        d_menu_principal.setObjectName("d_menu_principal")
        d_menu_principal.resize(480, 640)
        self.label = QtWidgets.QLabel(parent=d_menu_principal)
        self.label.setGeometry(QtCore.QRect(190, 20, 101, 18))
        self.label.setObjectName("label")

        self.retranslateUi(d_menu_principal)
        QtCore.QMetaObject.connectSlotsByName(d_menu_principal)

    def retranslateUi(self, d_menu_principal):
        _translate = QtCore.QCoreApplication.translate
        d_menu_principal.setWindowTitle(_translate("d_menu_principal", "Menu principal"))
        self.label.setText(_translate("d_menu_principal", "Menu princial"))
