# Form implementation generated from reading ui file 'usuario_crear.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_d_crear_usuario(object):
    def setupUi(self, d_crear_usuario):
        d_crear_usuario.setObjectName("d_crear_usuario")
        d_crear_usuario.resize(941, 328)
        self.label = QtWidgets.QLabel(parent=d_crear_usuario)
        self.label.setGeometry(QtCore.QRect(330, 20, 121, 31))
        self.label.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=d_crear_usuario)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 71, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=d_crear_usuario)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 161, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=d_crear_usuario)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 181, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=d_crear_usuario)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 111, 18))
        self.label_5.setObjectName("label_5")
        self.cb_tipo_usuario = QtWidgets.QComboBox(parent=d_crear_usuario)
        self.cb_tipo_usuario.setGeometry(QtCore.QRect(120, 160, 161, 26))
        self.cb_tipo_usuario.setObjectName("cb_tipo_usuario")
        self.cb_escuela = QtWidgets.QComboBox(parent=d_crear_usuario)
        self.cb_escuela.setGeometry(QtCore.QRect(190, 200, 351, 26))
        self.cb_escuela.setObjectName("cb_escuela")
        self.le_cedula_profesional = QtWidgets.QLineEdit(parent=d_crear_usuario)
        self.le_cedula_profesional.setGeometry(QtCore.QRect(160, 120, 221, 25))
        self.le_cedula_profesional.setObjectName("le_cedula_profesional")
        self.le_nombre_usuario = QtWidgets.QLineEdit(parent=d_crear_usuario)
        self.le_nombre_usuario.setGeometry(QtCore.QRect(60, 80, 181, 25))
        self.le_nombre_usuario.setObjectName("le_nombre_usuario")
        self.label_6 = QtWidgets.QLabel(parent=d_crear_usuario)
        self.label_6.setGeometry(QtCore.QRect(410, 120, 181, 18))
        self.label_6.setObjectName("label_6")
        self.le_cedula_especialidad = QtWidgets.QLineEdit(parent=d_crear_usuario)
        self.le_cedula_especialidad.setGeometry(QtCore.QRect(590, 120, 211, 25))
        self.le_cedula_especialidad.setObjectName("le_cedula_especialidad")
        self.label_7 = QtWidgets.QLabel(parent=d_crear_usuario)
        self.label_7.setGeometry(QtCore.QRect(250, 80, 141, 18))
        self.label_7.setObjectName("label_7")
        self.le_apellido_paterno = QtWidgets.QLineEdit(parent=d_crear_usuario)
        self.le_apellido_paterno.setGeometry(QtCore.QRect(390, 70, 191, 25))
        self.le_apellido_paterno.setText("")
        self.le_apellido_paterno.setObjectName("le_apellido_paterno")
        self.label_8 = QtWidgets.QLabel(parent=d_crear_usuario)
        self.label_8.setGeometry(QtCore.QRect(590, 70, 141, 18))
        self.label_8.setObjectName("label_8")
        self.le_apellido_materno = QtWidgets.QLineEdit(parent=d_crear_usuario)
        self.le_apellido_materno.setGeometry(QtCore.QRect(730, 60, 201, 25))
        self.le_apellido_materno.setObjectName("le_apellido_materno")
        self.pushButton = QtWidgets.QPushButton(parent=d_crear_usuario)
        self.pushButton.setGeometry(QtCore.QRect(790, 270, 131, 21))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(d_crear_usuario)
        QtCore.QMetaObject.connectSlotsByName(d_crear_usuario)

    def retranslateUi(self, d_crear_usuario):
        _translate = QtCore.QCoreApplication.translate
        d_crear_usuario.setWindowTitle(_translate("d_crear_usuario", "Crear usuario"))
        self.label.setText(_translate("d_crear_usuario", "# Usuario"))
        self.label_2.setText(_translate("d_crear_usuario", "Nombre:"))
        self.label_3.setText(_translate("d_crear_usuario", "Cedula profesional:"))
        self.label_4.setText(_translate("d_crear_usuario", "Esuela de procedencia:"))
        self.label_5.setText(_translate("d_crear_usuario", "Tipo usuario:"))
        self.label_6.setText(_translate("d_crear_usuario", "Cedula de especialidad:"))
        self.label_7.setText(_translate("d_crear_usuario", "Apellido paterno:"))
        self.label_8.setText(_translate("d_crear_usuario", "Apellido materno:"))
        self.pushButton.setText(_translate("d_crear_usuario", "Crear usuario"))
